# Generated by Django 5.2.5 on 2025-10-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
