# Generated by Django 5.2.5 on 2025-10-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
